-- MySQL Script generated by MySQL Workbench
-- Wed Jun 18 21:14:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema grupo_1_eventos_peligrosos
-- -----------------------------------------------------
USE `grupo_1_eventos_peligrosos` ;

-- -----------------------------------------------------
-- Table `grupo_1_eventos_peligrosos`.`calificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo_1_eventos_peligrosos`.`calificacion` ;

CREATE TABLE IF NOT EXISTS `grupo_1_eventos_peligrosos`.`calificacion` (
  `calificacion_id` INT NOT NULL AUTO_INCREMENT,
  `calificacion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`calificacion_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `grupo_1_eventos_peligrosos`.`canton`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo_1_eventos_peligrosos`.`canton` ;

CREATE TABLE IF NOT EXISTS `grupo_1_eventos_peligrosos`.`canton` (
  `canton_id` INT NOT NULL,
  `canton` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`canton_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `grupo_1_eventos_peligrosos`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo_1_eventos_peligrosos`.`categoria` ;

CREATE TABLE IF NOT EXISTS `grupo_1_eventos_peligrosos`.`categoria` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `grupo_1_eventos_peligrosos`.`categoria_via`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo_1_eventos_peligrosos`.`categoria_via` ;

CREATE TABLE IF NOT EXISTS `grupo_1_eventos_peligrosos`.`categoria_via` (
  `categoria_via_id` INT NOT NULL AUTO_INCREMENT,
  `categoria_via` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`categoria_via_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `grupo_1_eventos_peligrosos`.`causa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo_1_eventos_peligrosos`.`causa` ;

CREATE TABLE IF NOT EXISTS `grupo_1_eventos_peligrosos`.`causa` (
  `causa_id` INT NOT NULL AUTO_INCREMENT,
  `causa` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`causa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `grupo_1_eventos_peligrosos`.`estado_actual_via_o_inf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo_1_eventos_peligrosos`.`estado_actual_via_o_inf` ;

CREATE TABLE IF NOT EXISTS `grupo_1_eventos_peligrosos`.`estado_actual_via_o_inf` (
  `estado_actual_via_o_inf_id` INT NOT NULL AUTO_INCREMENT,
  `estado_actual_via_o_inf` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`estado_actual_via_o_inf_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `grupo_1_eventos_peligrosos`.`nivel_del_inf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo_1_eventos_peligrosos`.`nivel_del_inf` ;

CREATE TABLE IF NOT EXISTS `grupo_1_eventos_peligrosos`.`nivel_del_inf` (
  `nivel_del_inf_id` INT NOT NULL AUTO_INCREMENT,
  `nivel_del_inf` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nivel_del_inf_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `grupo_1_eventos_peligrosos`.`parroquia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo_1_eventos_peligrosos`.`parroquia` ;

CREATE TABLE IF NOT EXISTS `grupo_1_eventos_peligrosos`.`parroquia` (
  `parroquia_id` INT NOT NULL,
  `parroquia` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`parroquia_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `grupo_1_eventos_peligrosos`.`provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo_1_eventos_peligrosos`.`provincia` ;

CREATE TABLE IF NOT EXISTS `grupo_1_eventos_peligrosos`.`provincia` (
  `provincia_id` INT NOT NULL,
  `provincia` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`provincia_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `grupo_1_eventos_peligrosos`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo_1_eventos_peligrosos`.`tipo` ;

CREATE TABLE IF NOT EXISTS `grupo_1_eventos_peligrosos`.`tipo` (
  `tipo_id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tipo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `grupo_1_eventos_peligrosos`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo_1_eventos_peligrosos`.`evento` ;

CREATE TABLE IF NOT EXISTS `grupo_1_eventos_peligrosos`.`evento` (
  `evento_id` INT NOT NULL AUTO_INCREMENT,
  `provincia_id` INT NOT NULL,
  `canton_id` INT NOT NULL,
  `parroquia_id` INT NOT NULL,
  `causa_id` INT NOT NULL,
  `calificacion_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  `categoria_via_id` INT NOT NULL,
  `estado_actual_via_o_inf_id` INT NOT NULL,
  `nivel_del_inf_id` INT NOT NULL,
  `comunidad_barrio_sector` TEXT NULL,
  `latitud` DECIMAL(10,8) NULL,
  `longitud` DECIMAL(10,8) NULL,
  `fecha` DATE NULL,
  `numero_informe_provincial` VARCHAR(255) NULL,
  `fallecidas` INT NULL,
  `heridas` INT NULL,
  `personas_desaparecidas` INT NULL,
  `familias_afectadas` INT NULL,
  `personas_afectadas_directamente` INT NULL,
  `afectadas_indirectas` INT NULL,
  `familias_damnificadas` INT NULL,
  `personas_damnificadas` INT NULL,
  `personas_evacuadas` INT NULL,
  `personas_albergadas` INT NULL,
  `p_en_familias_acogientes` INT NULL,
  `p_en_otros_medios` INT NULL,
  `p_en_proceso_evacuacion` INT NULL,
  `p_resisten_evacuacion` INT NULL,
  `viviendas_afectadas` INT NULL,
  `viviendas_destruidas` INT NULL,
  `establecimientos_educativos_afectados` INT NULL,
  `establecimientos_educativos_destruidos` INT NULL,
  `centros_salud_afectados` INT NULL,
  `centros_salud_destruidos` INT NULL,
  `puentes_afectados` INT NULL,
  `puentes_destruidos` INT NULL,
  `bienes_publicos_afectados` INT NULL,
  `bienes_publicos_destruidos` INT NULL,
  `bienes_privados_afectados` INT NULL,
  `bienes_privados_destruidos` INT NULL,
  `metros_lineales_vias_afectadas` DECIMAL NULL,
  `ha_cultivo_afectadas` INT NULL,
  `ha_cultivo_perdidas` INT NULL,
  `ha_cobertura_vegetal_quemada` INT NULL,
  `animales_afectados` INT NULL,
  `animales_muertos` INT NULL,
  `descripcion_general` TEXT NULL,
  `macroevento` VARCHAR(255) NULL,
  `via_alterna` VARCHAR(255) NULL,
  PRIMARY KEY (`evento_id`),
  INDEX `fk_evento_provincia_idx` (`provincia_id` ASC) VISIBLE,
  INDEX `fk_evento_canton1_idx` (`canton_id` ASC) VISIBLE,
  INDEX `fk_evento_parroquia1_idx` (`parroquia_id` ASC) VISIBLE,
  INDEX `fk_evento_causa1_idx` (`causa_id` ASC) VISIBLE,
  INDEX `fk_evento_calificacion1_idx` (`calificacion_id` ASC) VISIBLE,
  INDEX `fk_evento_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_evento_tipo1_idx` (`tipo_id` ASC) VISIBLE,
  INDEX `fk_evento_categoria_via1_idx` (`categoria_via_id` ASC) VISIBLE,
  INDEX `fk_evento_estado_actual_via_o_inf1_idx` (`estado_actual_via_o_inf_id` ASC) VISIBLE,
  INDEX `fk_evento_nivel_del_inf1_idx` (`nivel_del_inf_id` ASC) VISIBLE,
  CONSTRAINT `fk_evento_provincia`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `grupo_1_eventos_peligrosos`.`provincia` (`provincia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_canton1`
    FOREIGN KEY (`canton_id`)
    REFERENCES `grupo_1_eventos_peligrosos`.`canton` (`canton_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_parroquia1`
    FOREIGN KEY (`parroquia_id`)
    REFERENCES `grupo_1_eventos_peligrosos`.`parroquia` (`parroquia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_causa1`
    FOREIGN KEY (`causa_id`)
    REFERENCES `grupo_1_eventos_peligrosos`.`causa` (`causa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_calificacion1`
    FOREIGN KEY (`calificacion_id`)
    REFERENCES `grupo_1_eventos_peligrosos`.`calificacion` (`calificacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `grupo_1_eventos_peligrosos`.`categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `grupo_1_eventos_peligrosos`.`tipo` (`tipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_categoria_via1`
    FOREIGN KEY (`categoria_via_id`)
    REFERENCES `grupo_1_eventos_peligrosos`.`categoria_via` (`categoria_via_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_estado_actual_via_o_inf1`
    FOREIGN KEY (`estado_actual_via_o_inf_id`)
    REFERENCES `grupo_1_eventos_peligrosos`.`estado_actual_via_o_inf` (`estado_actual_via_o_inf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_nivel_del_inf1`
    FOREIGN KEY (`nivel_del_inf_id`)
    REFERENCES `grupo_1_eventos_peligrosos`.`nivel_del_inf` (`nivel_del_inf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
